### ISSUE TITLE
KeyError: 1

### ISSUE THREAD

**Issue by hardianlawi** [marcotcr/lime#106]
Hi,

Sometimes, I could get this error when trying to use the method `as_pyplot_figure`. However, it works if I get another random sample, while sometimes it still does not.

`---------------------------------------------------------------------------`
`KeyError                                  Traceback (most recent call last)`
`<ipython-input-16-932d824cc008> in <module>()`
`----> 1 exp.as_list()`

`/usr/local/lib/python2.7/dist-packages/lime/explanation.pyc in as_list(self, label, **kwargs)`
`    132         """`
`    133         label_to_use = label if self.mode == "classification" else self.dummy_label`
`--> 134         ans = self.domain_mapper.map_exp_ids(self.local_exp[label_to_use], **kwargs)`
`    135 `
`    136         return ans`

`KeyError: 1`

The way I generate the instance that I want to explain is
`i = np.random.randint(0, test.shape[0])`
`samp = Xtest.iloc[i]`

and then the `explain_instance` is below
`exp = explainer.explain_instance(samp.as_matrix(), new_clf.predict_proba, num_features=10, top_labels=1)`
`exp.as_pyplot_figure()`

I am trying to get some consistency here. Any suggestion?

**Comment by marcotcr** [comment]
exp.as_list takes as its parameter the label for which you want an explanation. Since you're calling explain_instance with top_labels=1, it only produces an explanation for the top prediction of new_clf. If that is label 1, exp.as_list() will work, as the default parameter is one. If it is not, you'll get a key error. Your options:
1. If you're doing binary classification, don't use the top_labels parameter. You'll always get explanations for label 1
2. If it's multilabel classification, call exp.as_list(new_clf.predict(samp.as_matrix())[0])
3. If you want multiple explanations for different labels, call explain_instance with top_labels=num_labels
