### ISSUE TITLE
Classifier Vs Regressor

### ISSUE THREAD

**Issue by sourabhsparkala** [marcotcr/lime#118]
Hello,

I am new to this concept of Classification and Regression. I was going through the paper of "Why Should I Trust You?": Explaining the Predictions of Any Classifier. It clearly describes the idea behind the Implementation of Agnostic-Model explanations. 

However, I was wondering if there is any related paper to regression or would you mind providing me a broader idea of how the Classifier Learning method varies from Regression Learning model using Lime?

An overview or an example would be really helpful.

Thanks and Regards
Sourabh

**Comment by marcotcr** [comment]
I can't think of of any papers that deal with interpretability in a regression setting. Have you seen [this notebook](https://marcotcr.github.io/lime/tutorials/Using%2Blime%2Bfor%2Bregression.html), and compared it to the classification notebooks we have?

**Comment by Sandy4321** [comment]
link you recommend https://marcotcr.github.io/lime/tutorials/Using%2Blime%2Bfor%2Bregression.html
is crushing due to error

explainer = lime.lime_tabular.LimeTabularExplainer(train, feature_names=boston.feature_names, class_names=['price'], categorical_features=categorical_features, verbose=True, mode='regression')
 
 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-7f0086557ce4> in <module>()
----> 1 explainer = lime.lime_tabular.LimeTabularExplainer(train, feature_names=boston.feature_names, class_names=['price'], categorical_features=categorical_features, verbose=True, mode='regression')
 
C:\Anaconda3\lib\site-packages\lime\lime_tabular.py in __init__(self, training_data, mode, training_labels, feature_names, categorical_features, categorical_names, kernel_width, verbose, class_names, feature_selection, discretize_continuous, discretizer, random_state)
    148         self.mode = mode
    149         self.categorical_names = categorical_names or {}
--> 150         self.categorical_features = categorical_features or []
    151         self.feature_names = feature_names or [str(i) for i in range(training_data.shape[1])]
    152 
 
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by marcotcr** [comment]
fixed

**Comment by mstaniak** [comment]
@sourabhsparkala You might be also interested in this project https://github.com/MI2DataLab/live
