### ISSUE TITLE
Add a feature in Tabular Explainer to deal with missing values?

### ISSUE THREAD

**Issue by hangyao** [marcotcr/lime#122]
Hi Lime team,

When using a tree-based model (Xgbost or LightGBM), missing values can be automatically binned and processed. However, the Tabular Explainer doesn't allow the existence of missing values and will throw an exception: `Input contains NaN, infinity or a value too large for dtype('float64').`

Filling any missing values with  `fillna()` in such case will cause incorrect explanations. Is there any way to deal with that?

Thank you!

**Comment by marcotcr** [comment]
Uh, good question. I don't know what to do with missing values, maybe we could support them and sample them just like we do any other values if the feature is categorical. For numerical features though, I don't know. We could maybe assume the frequency of missing values and sample MISSING at that rate, and do what we're doing otherwise.

Anyway, this is not something I can see myself working on soon. If you are interested, we'll take a pull request : )
