### ISSUE TITLE
LimeTabularExplainer with dummy variables?

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [marcotcr/lime#166]
I would like to use the LIME tabular explainer on a classifier and feature-set that includes numeric and dummy/indicator variables. 

The tutorial for LIME tabular explainer (https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20continuous%20and%20categorical%20features.html) mentions numeric variables and categorical variables. I could pass the dummy variables as 'numeric', but the tutorial says the explainer will base explanations on the mean and standard deviation. The mean of a dummy variable is certainly meaningful, but I don't think the standard deviation is.

Alternatively, I could do an inverse dummy-encoding to collapse sets of dummy variables back into categorical columns, but ideally would prefer not to do this.

Is there a recommended way to handle dummy/indicator variables with LIME tabular explainer?

Thanks!

**Comment by marcotcr** [comment]
Assuming your dummy variables are the result of encoding some categorical feature, you have to collapse it back to categorical columns. The reason is that LIME will perturb the example in ways that will be nonsensical if you leave the variables encoded. For example, let's say you encoded some variable size = {small, med, large} into three binary variables, so that [0, 0, 1] means large and [1, 0, 0] means small. If you just pass the encoded array into LIME, it will generate perturbed samples like [1, 1, 1], which have no meaning.

**Comment by MaxPowerWasTaken** [comment]
ok thanks for the answer.

**Comment by ybwlrs** [comment]
Marco, i believe a related question to this thread.
In TensorFlow some of the features are constructed and only generated in runtime (Bucketing certain variable, crossing, one hot encoding etc). That means that in the "train" numpy array that is passed to the tabular explainer they do not exist. Do I need to recreate them and add them to that array?
Also does the "train" numpy array has to contain only the features used?

Unrelated, i get "TypeError: can't multiply sequence by non-int of type 'float'" from the discretize.py .. any quick idea why?

Thanks
