### ISSUE TITLE
How to interpret feature contribution values when using continous data?

### ISSUE THREAD

**Issue by lindskogniklas** [marcotcr/lime#177]
Hi!

I’ve been using the Python version of LIMEs LimeTabularExplainer to understand the classification predictions of a RF model trained on a data set with features containing continuous data. However, the results have been a bit confusing, so I wonder if you could enlighten me.

It is my understanding that the features with the highest contribution to the predicted probability in the locality of the selected sample is shown by the explainer. Each of these contribution values is created by taking the weight of a feature multiplied with the scaled feature value. Is this correct?

The tutorials on github suggests there is a strong correlation between the predicted probability and the contribution of features.
In my case however, the contributions are predicted to be very small, with top features having contribution <= 0.02.

Given this, I guess my confusion boils down to the following the following questions:
•	How should one interpret the contribution of each feature in the linear model? 
        o	Should it always be interpreted as the approximated value of how much a certain feature contributes to the prediction?
        o	Is there a difference on how to interpret the contribution of features if they are discretized or continuous?
•	If the contribution values are low for the top features, does this mean that the “best” features have little impact on the predicted probability? And if yes, why could this be?
•	Can highly correlated features be an error source in the prediction of the linear model or is this taken into account in the contribution weights somehow?

Best Regards
Niklas

**Comment by marcotcr** [comment]
> It is my understanding that the features with the highest contribution to the predicted probability in the locality of the selected sample is shown by the explainer. Each of these contribution values is created by taking the weight of a feature multiplied with the scaled feature value. Is this correct?

Depends on what parameters you use for the explainer. By default, explanations are given on discretized data, so it's just the weight (as the feature is binary). Otherwise I think the default is as you said, weight * scaled feature value.

> The tutorials on github suggests there is a strong correlation between the predicted probability and the contribution of features.
In my case however, the contributions are predicted to be very small, with top features having contribution <= 0.02.

It depends on the model. If the model is very smooth, and each feature only has a small contribution, you would see what you are describing. Another situation where this might happen is if the intercept is dominating the explanation (i.e. if the model tends to predict a certain label regardless of the evidence).


> How should one interpret the contribution of each feature in the linear model?
Should it always be interpreted as the approximated value of how much a certain feature contributes to the prediction?

I think the better way to interpret the explanation is as a local linear approximation of the model. Rather than saying 'feature x contributes X', I think of it as 'if I change feature X to other values, this weight is the reverse of the expected effect'.

> Is there a difference on how to interpret the contribution of features if they are discretized or continuous?

Yes. Contributions for continuous features are trickier to interpret because you have to think in terms of standardized data, and also there may be 'double negatives' (i.e. the feature value is negative in standardized data, and the feature weight is also negative). On the other hand, for discretized data you don't get an idea of the direction of a change, only of the weight of that particular slice vs all other slices.

> If the contribution values are low for the top features, does this mean that the “best” features have little impact on the predicted probability? And if yes, why could this be?

Yes. Read my comments above as to possible reasons for this. 

> Can highly correlated features be an error source in the prediction of the linear model or is this taken into account in the contribution weights somehow?

Highly correlated features should not be a problem for the linear model, especially if you use lasso_path as a feature selection procedure (but warning: lasso may just choose one of the features arbitrarily and drop the other). See also #178
