### ISSUE TITLE
Dealing With Highly Correlated Features

### ISSUE THREAD

**Issue by sudhanshunathmishra** [marcotcr/lime#178]
1) One cannot interpret the coefficients of features in a multiple regression model if features are highly correlated. Therefore, is it correct to assume that coefficients generated by the LIME approximations are not meaningful in such scenarios? 

For e.g. It would not be meaningful to interpret the impact of the unit change in Feature A if one cannot hold Feature B constant at the same time. (Imagine Feature A is a person's height and Feature B is a person's surface area)

2) Why does LIME use ridge-regression instead of regular OLS? Is it to deal with the multicollinearity issue? 

3) Currently, LimeTabularExplainer uses feature_selection = 'auto' by default. In case num_features >6, it uses 'highest_weights'. Could we use 'lasso_path' instead such that LIME automatically performs variable selection using L1 regularization to drop some of the highly correlated features? Why not use Elastic Net?

**Comment by marcotcr** [comment]
I guess I answered this in an email and forgot to post here.

1. The fact that the features are correlated should be ok, provided you don't mind if LIME picks one of them arbitrarily as an explanation (using lasso).
The problem I see in what you described is that features are so heavily correlated that perturbed samples will be nonsensical if you just throw this representation into LIME (one example I've seen in another dataset is perturbed samples that resulted in 'marital-status=single', 'relationship=husband').
In this case, I think the thing to do is to re-featurize the data just for perturbation. 

2. I think it's just good practice - there could be multicollinearity, OLS can get unstable depending on the underlying optimization, etc

3. I would use lasso path if you're concerned about correlated features, but `highest_weights` is much faster and a good enough hack for most use cases (which is why it's the default)
