### ISSUE TITLE
How to use lime with Tensorflow ?

### ISSUE THREAD

**Issue by monk1337** [marcotcr/lime#200]
All of the examples are showing use case with keras , I couldn't find any tutorial or demo which is using tensorflow with lime , can you please explain how i can use lime with tensorflow ?

So  here is very simple rnn_lstm example code : 

```
import tensorflow as tf
from tensorflow.contrib import rnn
import numpy as np
num_units=100
tf.reset_default_graph()
x_input = tf.placeholder(name='input_', shape=[None, 2, 2], dtype=tf.float32)
labels = tf.placeholder(name='labels', shape=[None], dtype=tf.float32)
with tf.variable_scope('encoder') as scope:
    cell = rnn.LSTMCell(num_units=num_units)
    output = tf.nn.dynamic_rnn(cell, x_input, dtype=tf.float32)
    output=tf.transpose(output[0],[1,0,2])
    result=output[-1]
    
    full_connected=tf.get_variable(name='fully_connected',shape=[num_units,2],dtype=tf.float32,initializer=tf.random_uniform_initializer(-0.01,0.01))
    bias = tf.get_variable(name='bias',shape=[2],initializer=tf.random_uniform_initializer(-0.01,0.01))
    
    projection = tf.matmul(result,full_connected)+bias
    
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    out=sess.run(projection,feed_dict={x_input:np.random.randint(0,3,[3,2,2]),labels:np.random.randint(0,2,[2])})
    print(out)
```

Which is binary classification , Now if i want to use lime here what should be my argument for model ?
Can you show me example for this code ?

I tried something like this:

```
import tensorflow as tf
from tensorflow.contrib import rnn
from lime.lime_text import LimeTextExplainer

import numpy as np
num_units=100
X_train=np.random.randint(0,3,[3,2,2])
y_train=np.random.randint(0,2,[2])
data_columns = ['yes','no']

tf.reset_default_graph()
x_input = tf.placeholder(name='input_', shape=[None, 2, 2], dtype=tf.float32)
labels = tf.placeholder(name='labels', shape=[None], dtype=tf.float32)
with tf.variable_scope('encoder') as scope:
    cell = rnn.LSTMCell(num_units=num_units)
    output = tf.nn.dynamic_rnn(cell, x_input, dtype=tf.float32)
    output=tf.transpose(output[0],[1,0,2])
    result=output[-1]
    
    full_connected=tf.get_variable(name='fully_connected',shape=[num_units,2],dtype=tf.float32,initializer=tf.random_uniform_initializer(-0.01,0.01))
    bias = tf.get_variable(name='bias',shape=[2],initializer=tf.random_uniform_initializer(-0.01,0.01))
    
    projection = tf.matmul(result,full_connected)+bias
    
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    out=sess.run(projection,feed_dict={x_input:X_train,labels:y_train})
    print(out)
    explainer = LimeTextExplainer(class_names=data_columns)

    exp = explainer.explain_instance(X_train[1], out, num_features=2, labels=(1,))
```

But getting error:

`TypeError: cannot use a string pattern on a bytes-like object
`

How to properly use on tensorflow ?

**Comment by mookfon** [comment]
Hello, 

first of all do you want to produce explanation for a textual input or a tabular input (ie categorical and numerical features) ? Because if you wan to use a textual input, you have to use `LimeTextExplainer` like you did but it you want to use tabular input, then you must use `LimeTabularExplainer`. 

Let's consider you wanted to use `LimeTabularExplainer`. Then, If we look at the docstring of the `LimeTabularExplainer.explain_instance()` method we can read:

> predict_fn – prediction function. For classifiers, this should be a function that takes a numpy array and outputs prediction probabilities. For regressors, this takes a numpy array and returns the predictions. For ScikitClassifiers, this is classifier.predict_proba(). For ScikitRegressors, this is regressor.predict().

You have to give a to LIME the function linking input to probability prediction because LIME work by perturbing the input and measuring the effect it has on those probabilities.

In your code, you passed the output node of your Tensorflow graph to `explain_instance()`: `exp = explainer.explain_instance(X_train[1], out, num_features=2, labels=(1,))`. Rather, you should wrap your Tensorflow code in a function that takes a numpy array as input, and ouput another numpy array, where each line correspond to the probabilities of your different classes for one sample. So you could do something like this:

```
def predict_proba(X):
    x_input = tf.placeholder()
    ... build your network here ...
    projection = tf.matmul(result,full_connected

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        out=sess.run(projection,feed_dict={x_input:X})
    return out 
``` 
Then you do: `exp = explainer.explain_instance(X_train, predict_proba, num_features=2, labels=(1,))`, making sure that `X_train` has the right dimensions.

If you wanted to use `LimeTextExplainer`, the reasoning would be the same the same but each row in your `X_train` should be a string. 

_Note_: I don't think your `projection` Variable holds a valid probability distribution (i.e the rows have to sum to 1), and that's needed for using LIME.
