### ISSUE TITLE
feature effect polarity switch with or without discretize continous feature

### ISSUE THREAD

**Issue by xiaokunx** [marcotcr/lime#202]
I'm following the notebook [[Using Lime for regression.ipynb](https://github.com/marcotcr/lime/blob/master/doc/notebooks/Using%20lime%20for%20regression.ipynb)]. Out of curiosity, I want to contrast the explanation of the RF model, with and without discretize the continous features.

test instance:
```python
df = pd.DataFrame(boston.data, columns=boston.feature_names)
df['price'] = boston.target
i=25
print('test instance:')
print(df.loc[i,:])

test instance:
CRIM         0.84054
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.59900
AGE         85.70000
DIS          4.45460
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          303.42000
LSTAT       16.51000
price       13.90000
Name: 25, dtype: float64
```

With the discretize_contious set to be **False**, the LSTAT seems to be a negative feature for the test case, whereas the RM to be positive.

```python
explainer = lime.lime_tabular.LimeTabularExplainer(train, 
                                                   feature_names=boston.feature_names, 
                                                   class_names=['price'], 
                                                   categorical_features=categorical_features, 
                                                   verbose=True,
                                                   discretize_continuous=False,
                                                   mode='regression')
i = 25
exp = explainer.explain_instance(test[i], rf.predict, num_features=5)
exp.show_in_notebook()
exp.as_list()
```
The results are:
```
[('LSTAT', -4.570606085886164),
 ('RM', 2.292133497790679),
 ('DIS', -1.557538500317858),
 ('TAX', -0.3926067323381221),
 ('NOX', -0.3398315266006181)]
```
![screen shot 2018-06-21 at 4 42 36 pm](https://user-images.githubusercontent.com/2426516/41750710-3a30db4c-7572-11e8-9773-ae6e8de660c2.png)

With the discretize_contious set to be **True**, the LSTAT feature (quartile bins) seems to be a positive feature  whereas the RM (quartile bin) seems to be negative.

```python
explainer = lime.lime_tabular.LimeTabularExplainer(train, 
                                                   feature_names=boston.feature_names, 
                                                   class_names=['price'], 
                                                   categorical_features=categorical_features, 
                                                   verbose=True,
                                                   discretize_continuous=True,
                                                   mode='regression')
i = 25
exp = explainer.explain_instance(test[i], rf.predict, num_features=5)
exp.show_in_notebook()
exp.as_list()
```
The results are:
```
[('7.20 < LSTAT <= 11.68', 1.8680328480113486),
 ('6.21 < RM <= 6.62', -1.1938058217045235),
 ('PTRATIO <= 17.40', 0.8789287973098316),
 ('DIS > 5.22', -0.6775599375038154),
 ('391.18 < B <= 395.94', 0.5510605990604857)]
```
![screen shot 2018-06-21 at 4 45 22 pm](https://user-images.githubusercontent.com/2426516/41750773-8b367f24-7572-11e8-8862-810806a3dc14.png)

Could you help understand why the discretization cased the sign to flip? Is is due the the sample difference (discretization make the n-dim feature space more isotropical?), or change in the fitting of the local approximation function? or both? 

Thank you!

**Comment by marcotcr** [comment]
You printed df.loc[25] but used test[25] for explaining, so the values you showed under 'test instance' are not the same as the ones being displayed in the explanation. This doesn't matter, just pointing it out to avoid confusion.

This is one the reason why we discretize by default, interpreting coefficients for non-discretized data is tricky. The coefficients are computed using standardized values, i.e. the first explanation is saying something like 'for every standard deviation increase in LSAT, the prediction goes down by 4.57'. However, the instance has `LSAT=7.39`, where the mean of the dataset is `LSAT=12.65`. I think what is going on is that the contribution of `LSAT=7.39` is positive from the baseline because of the double negative. 

If you increase LSAT, the predicted value will go down. Since the instance being explained has LSAT lower than average, the 'contribution' of a low LSAT to the predicted value is positive.
