### ISSUE TITLE
How to interpret LIME result in regression?

### ISSUE THREAD

**Issue by vinhqdang** [marcotcr/lime#225]
Hello everyone,

In the notebook: https://marcotcr.github.io/lime/tutorials/Using%2Blime%2Bfor%2Bregression.html

How should I interpret the result (in cell number 12)?

For instance, take the most important feature ``'6.99 < LSTAT <= 11.43'``. Does it mean that, because ``LSTAT`` is between ``6.99`` and ``11.43`` so it makes the predicted value towards ``higher direction`` a value of ``1.76``?

Thanks

**Comment by marcotcr** [comment]
Yes, it makes the predicted value towards the right higher by 1.76, as compared to what it would be on aveage for other values of this feature (since it is discretized).
For regression, it probably makes more sense not to discretize, I should not have used discretization in the tutorial. With no discretization, there is a caveat that LIME scales the data, so the coefficients in the explanations are w.r.t. scaled data.
