### ISSUE TITLE
Understanding Lime Output

### ISSUE THREAD

**Issue by jrs64719** [marcotcr/lime#246]
I am just trying to get a better understanding of the output for Lime Explainer. Below is an output i received shows that the majority of the feature are favorable for a predicted value of 0, but the predicted value from the gradient boost model is .9.
![lime output](https://user-images.githubusercontent.com/34696112/47307395-271cd800-d5ec-11e8-8cd1-18424b0837e5.PNG)

**Comment by marcotcr** [comment]
That is because there is an intercept (not shown in the visualization, but available through `explanation.intercept` that in this case is most likely very high towards class one (i.e. the model tends to predict 1 around this vicinity)

**Comment by pratapkishorevarma** [comment]
@marcotcr When intercept is high, how do we interpret the feature weights?
The features with negative weights will be more in this case. Does it mean the explanation is wrong? 
When the intercept is low and there are more positives it's easy to understand the features contributed to it and against it, but when there are more negatives how should we interpret the result?

**Comment by henry16lin** [comment]
@marcotcr  I have the similar question.  Below figure is an output of I applied LIME on Titanic dataset with random forest model.
explanation.intercept give me :  {1: 0.8212393105581415}
The negative features seem to not strong enough to offset the intercept but the model prediction is '0'.
How could I explain this case? or it might be caused by underfitting of explainer?
![image](https://user-images.githubusercontent.com/47073122/67637788-0c74f180-f919-11e9-9f71-0005512f8fb3.png)

**Comment by marcotcr** [comment]
The way to interpret a high intercept is: in the region close to this instance, most predictions are positive. The features with negative weights counter that effect to some extent.
