### ISSUE TITLE
Fails to display in notebook - Object of type 'ndarray' is not JSON serializable

### ISSUE THREAD

**Issue by ukamath** [marcotcr/lime#272]
Hello
I have a deep learning classifier using Keras (TensorFlow), I am able to get the explanation using basic text but note in the pretty UI 
What works
```
from lime.lime_text import LimeTextExplainer
explainer = LimeTextExplainer(class_names=TEXT_LABELS)
```

```
def new_predict(texts):
  _seq = tk.texts_to_sequences(texts)
  _text_data = pad_sequences(_seq, maxlen=MAX_LEN)
  return single_channel_kim_model.predict(_text_data)

exp = explainer.explain_instance('forget reservations thank great company i have cancelled flighted flight once again thank you',
                                 new_predict,
                                 num_features=7,
                                 labels=[0, 2]
                                )

print ('Explanation for class %s' % TEXT_LABELS[0])
print ('\n'.join(map(str, exp.as_list(label=0))))
print ()
print ('Explanation for class %s' % TEXT_LABELS[2])
print ('\n'.join(map(str, exp.as_list(label=2))))
```

When I use 
`exp.show_in_notebook(text='forget reservations thank great company i have cancelled flighted flight once again thank you', labels=(0,))` 
It throws TypeError: Object of type 'ndarray' is not JSON serializable
Thanks

**Comment by engmubarak48** [comment]
Similar Issue here too 

TypeError: Object of type 'int64' is not JSON serializable

**Comment by marcotcr** [comment]
What's the python version and LIME version? I'll try to replicate

**Comment by engmubarak48** [comment]
I have fixed the issue, I don't think it was about versions. you just have to make sure your data type before you feed it to your the LimeTabularExplainer. In my case, categorical_names in LimeTabularExplainer was int64 [0, 1], instead of [no, yes]. I realize this parameter should be a Unicode data type. So .astype('U') helped.

**Comment by paramita-c** [comment]
I was getting the same error while trying to use LIME in Titanic data set (which had a mix of numeric and categorical variables)
LimeTabularExplainer expects all the numeric attributes to be as float64 format in order to be displayed using show_in_notebook method. So convert all the int64 features (including the target variable) to np.float64 type before starting to build and interpret models using LIME.
I have used LIME to interpret my models for Titanic data set, entire code (data cleaning, preprocessing, feature engineering, interpreting with LIME) can be found in my github account

**Comment by ommehaz** [comment]
This is whats happening to me now. I am following this tutorial: https://marcotcr.github.io/lime/tutorials/Lime%20-%20basic%20usage%2C%20two%20class%20case.html 
 In step number 10, instead of exp.as_list() I do exp.as_html() and the error is that it can’t serialize to json. I am using the latest python version 3 (32 bit). Can you help?

**Comment by marcotcr** [comment]
Just made some changes that should help, try pulling from 51c21f31b6a9c7ff86c223d39bdddb1d3cd1da72 and installing. Make sure your class names and categorical names are not int64.
If still having trouble, reopen the issue.
