### ISSUE TITLE
Generate a subplot display with as_pyplot_figure()

### ISSUE THREAD

**Issue by ivan-marroquin** [marcotcr/lime#288]
Hi @marcotcr ,

Many thanks for making available such great analytical tool! I have a simple request: how can I generate a subplot with as_pyplot_figure()? For example, I analyzed the results of a multi-class MLP network. There are three classes for which I use the commands:

exp_Model_1.as_pyplot_figure(label= 0)
exp_Model_1.as_pyplot_figure(label= 1)
exp_Model_1.as_pyplot_figure(label= 2)

That works fine. But, I would like to do something like this:
plt.figure()
plt.subplot(3,1,1)
exp_Model_1.as_pyplot_figure(label= 0)
plt.subplot(3,1,2)
exp_Model_1.as_pyplot_figure(label= 1)
plt.subplot(3,1,3)
exp_Model_1.as_pyplot_figure(label= 2)

Unfortunately, it is not working. Do you have another suggestion?

I am using Python 3.6.5 and matplotlib 2.2.2

Kind regards,

Ivan

**Comment by marcotcr** [comment]
`as_pyplot_figure` calls `plt.figure`, which is why your subplot does not work.
What I recommend doing if you want more flexibility is to call `exp.as_list` and generate your own plots rather than calling `as_pyplot_figure`. You can use the code [here](https://github.com/marcotcr/lime/blob/master/lime/explanation.py#L155) as a template.
