### ISSUE TITLE
Default value of as_list() during submodular_pick

### ISSUE THREAD

**Issue by totifra** [marcotcr/lime#311]
Hi there,

I am wondering if it is correct that the desired label for exp.as_list() during submodular pick should always be 1 when creating the explanation matrix W (l.103 in submodular_pick.py). What is if we are dealing with a multiclass problem and the correct label would be 0? Shouldn't we use then the explanation for label 0 instead of label 1? Do I miss something?

(I am using submodular pick for a multiclass problem using LimeTabularExplainer)

Bests
Thomas

**Comment by marcotcr** [comment]
This may indeed be a problem if there are more than 2 labels, but with 2 labels the explanation of 0 is always the negative of the explanation for 1 (and the sign does not matter because we take the absolute value in line 118).

In any case, this is a bug. Line 70 should have `top_labels=1`, and line 103 should be something like `exp.as_list(label=exp.available_labels()[0])`.
Do you want to author a pull request with this minor changes? If not, I can do it myself later.

Thanks

**Comment by totifra** [comment]
Thanks for your responding so quickly and already having a solution in your mind. I would be thankful if you would author the pull request.

**Comment by totifra** [comment]
Is it necessary to add `top_labels=1` to line 70? Because then the output will only have explanations for one label. But sometimes it is also nice to see the explanations for other labels. I guess your proposed change of line 103 should be sufficient to fix the computation of the matrix W. What do you think?

**Comment by marcotcr** [comment]
Fixed in 813fbd0f4f1b0499065fca1ca2159e20263bf8a8
I can't think of a case where I would want to pick explanations based on features that explains classes that were not predicted, but if needed one can use the `top_labels` parameter in the init of `SubmodularPick`.
