### ISSUE TITLE
Question regarding representation of categorical features

### ISSUE THREAD

**Issue by EoinKenny** [marcotcr/lime#323]
Hi, I appreciate you area all busy and I would like to thank you in advance if you have the time to reply.

In the example notebooks, for categorical features the dataset is not one hot encoded (ohe) when put into the LimeTabularExplainer object, instead it is only ohe in the actual model.

If I were to ohe the dataset's categorical features, and make a black box model with that, then I put that ohe representation of `X_train` into the LimeTabularExplainer object, will that ruin the results really? I would label each binary ohe column in the `categorical_features=[x_1,x_2,...x_n]` parameter list. My experience so far is that the explanations are still reasonable?

My understanding is that the notebook examples here do it in a particular way for visualisation purposes? Or is there an underlying mechanical reason you can't put the ohe representation into the LimeTabularExplainer object?

Thanks

**Comment by lrnzcig** [comment]
In my experience, you could indeed pass the ohe columns to the explainer and get something decent as an explanation... However when you do it the right way, you really notice the difference, since when a categorical feature is perturbed by Lime, it actually changes from one value to another, i.e. as if you changed 2 ohe columns at the same time, but exactly 2.

On the other hand, it is not so difficult to adapt, your don't need to retrain the model, just pass a predict function that does the ohe first (in the same other) and then launches the model.

Hope it helps.

**Comment by marcotcr** [comment]
The explanation may be still be reasonable by luck, but you may get perturbations that create invalid inputs (and the explanation will be based on those). Let's say that you encode the variable 'sex'  with one hot encoding, such that [1, 0] is male and [0, 1] is female. If you just use LIME, we have no way of knowing that [1, 1] is a nonsensical input, and will likely generate this combination (which will give your model something invalid).

**Comment by EoinKenny** [comment]
Thanks for the replies, this answers my question perfectly.
