### ISSUE TITLE
Use LIME explainer with classifier from Google Lucid library

### ISSUE THREAD

**Issue by arybinski** [marcotcr/lime#353]
Hi, I tried to use LIME explainer to explain predictions from google lucid image classifier. I got stuck trying that. I'm sending a google colab link that can recreate my problem.
https://colab.research.google.com/github/arybinski/xai-notebooks/blob/master/Lucid_Lime.ipynb

My goal would be to get explanations and then mark important image sections as in other LIME notebook examples.

Could anyone more experienced in using LIME have a look and maybe give me some hints or advice on how to use LIME in this situation? I would greatly appreciate any help with it. 
If this kind of question is not for this issue tracker, please let me know.

**Comment by marcotcr** [comment]
You need the prediction function that is used in `explain_instance` to take as input a set of images rather than a single image. The error message is telling you LIME is giving you a (10, 224, 224, 3) array (10 images), while your function takes in one image (224, 224, 3).
I don't know lucid, but I would guess they probably have a function to classify more than one image at a time. If not, you can just wrap your function.

Furthermore, the output of your prediction function should be an (n, d) array, where n is the number of input instances and d is the number of classes in the problem. It's fine if you want to make it binary (d=2) or leave it as (d=1001), but your current prediction function is returning the top prediction probabilities for the top 10 classes, which could change for different images or different perturbations of the same image.
