### ISSUE TITLE
Does LIME support  recommender system?

### ISSUE THREAD

**Issue by joshvemula** [marcotcr/lime#380]
Can LIME be used for recommendation system to give explanations why the particular recommendation is provided? If yes, could you provide an example?. If no, kindly provide the reason for not supporting.

**Comment by marcotcr** [comment]
Depends on the recommender system. In some systems (I'm thinking the traditional collaborative filtering based on matrix factorization) there is no input `x` such that you get a prediction `f(x)`. For other systems (e.g. as content-based) you can get `f(x)` for an arbitrary `x`, in which case LIME can be used. We must be able to perturb the input and get new predictions. 

It also depends if the output is a score (in which case it is easier, because  a recommender system can be viewed as a simple regressor) or a ranked list (in which case explanation becomes harder, you end up having to explain properties such as 'what contributes towards the high rank of this particular item').
