### ISSUE TITLE
Code for image data (super-pixels)?

### ISSUE THREAD

**Issue by dsmilkov** [marcotcr/lime#4]
Looks like the code only works for text or tabular data. Do you plan to open source code that works with image data?

Thanks!

**Comment by marcotcr** [comment]
I do, but I need to work on it so that it computes explanations in a reasonable time.
I am slammed for the following weeks, but I still plan on making it work on images well afterwards.
Thanks,

**Comment by mohmankum** [comment]
Hi Marco, Do you plan to release this anytime soon ?

**Comment by christophM** [comment]
Hi everyone
I wrote some code for explaining the classification of an image classifier and wanted to share it with you. I am using VGG16 trained on Imagenet as example. See here: https://github.com/christophM/explain-ml. 
The algorithm is close to LIME but there is some variation (For example for choosing the superpixels I simply choose every superpixel with a LASSO weight bigger than 0, instead of K-LASSO). Takes ca. 1 minute per image. 

Feel free to make pull requests and improve the code.

**Comment by asross** [comment]
Just want to add a 👍 , and also ask if there are plans to implement this soon or if a PR would be welcome. One way to improve the performance might be to precompute the superpixel segmentations, if that's one of the bottlenecks, since users will likely be re-explaining the same examples.

**Comment by marcotcr** [comment]
Interesting, I'll have to take a look at that repository to see if it would be easy to incorporate it here.
I feel bad that I said I would work on this 6 months ago, and never did - but I can't see myself doing this before the February conference deadlines. Pull requests are always welcome, of course.

**Comment by marcotcr** [comment]
Just added a version with [images](http://marcotcr.github.io/lime/tutorials/Tutorial%20-%20images.html).
