### ISSUE TITLE
Intercept and lower bounds for Image Explanation

### ISSUE THREAD

**Issue by palatos** [marcotcr/lime#411]
So this is actually two technical questions about the Image explanations and the ridge regression for that case.
Say that we have only two classes of images (0 and 1).

The first question is: Is there an upper/lower bound on the explanation weights for each segment in an image? I notice they frequently lay in the (-1,1) range, but I'm not sure if that is just a coincidence or intended. Could one get a segment in an image with a explanation/ridge coefficient of 5.0 for instance?

The second question is: How does the ridge regression intercept affect the explanations and their interpretation? For instance, can the user always assume that positive weights mean a segment contributes towards that given classification, and negative weights against it, or should one also check the intercept value for each class? Is there any case where a segment could have negative explanation weights but still be contributing positively towards a classification due to the intercept value, and vice versa?

**Comment by marcotcr** [comment]
1. Ridge is acting on prediction probabilities, which are between 0 and 1. I think it is possible to get a coefficient that does not lie in `(-1, 1)`, but very unlikely
2. It is possible for the intercept to be important, but positive weights still mean a segment contributes towards that given classification. What can happen is to only have negative weights because the intercept is quite high. See for example #304, #246.
The intercept is not per-segment, but for the whole instance, so I think the scenario you propose (a segment having negative weight and still be contributing positively) cannot happen.
