### ISSUE TITLE
Is there any way to get explanation for a few selected features?

### ISSUE THREAD

**Issue by xueyyyy** [marcotcr/lime#414]
I am currently working to make explanation for a multiple classifiers. The API I used is
lime.lime_tabular.LimeTabularExplainer.
The prediction model contains over 100 features, and the problem is that It takes too much time to run the explainer. Therefore I wonder is there any way to select some of the specific features for the explainer, and just ignore the others features?

**Comment by marcotcr** [comment]
We don't have that option built in, you would have to adapt the code so that it only perturbed a subset of features (shouldn't be very hard). I assume you want to do this so you can reduce the number of samples needed - the potential problem is if the features you choose to ignore are particularly important for the model. If you are sure that they are not important, you can write a wrapper for the predict_fn such that it takes only the features you want to explain, and inputs random values to the other features, and then use this wrapper with the explainer as is.
