### ISSUE TITLE
Multi-value categorical variables

### ISSUE THREAD

**Issue by bvanberl** [marcotcr/lime#425]
Hello,

I am working with the LIME tabular explainer API, as I have a mixture of numerical and categorical features in my dataset. How would I represent categorical features that may take on ≥ 0 values in a single example? I understand that the API requires categorical features to be converted 
 to an integer representation, but how would I represent combinations of values for one categorical feature? To illustrate the circumstance, see the example dataset below and consider the "Comorbidities" feature:

|  |SmokingStatus  | DrinksPerWeek         |         Comorbidities|
| ------------- |-------------| -----|------------|
|0 |       Smoker  |            0        |         [Hypertension]|
|1     |   Smoker      |        0 | [Hypertension, Heart Failure]|
|2   |  Nonsmoker  |            6        |        [Liver Failure]|
|3     |     Quit        |      9 | [Hypertension, Liver Failure]|
|4    | Nonsmoker | 2        |    []  |

One approach I investigated was to consider the presence of each value as its own binary categorical feature; however, the number of features scales up fast since I have multiple features with examples taking on many combinations of values. I am concerned that my approach does not enable efficient sampling around an example to be explained. I understand that LimeTabularExplainer requires that values in categorical columns be integers, but how would I encode these "multi-valued" categorical features as integers?

Thanks for considering my question and for maintaining this well-documented implementation of LIME!

**Comment by marcotcr** [comment]
For your example, it depends on whether you want the explanations to be in terms of groups of comorbidities or individual comorbidities. If you wanted groups, you could encode a group as you would a new feature, e.g.
> Hypertension = 0
> Heart Failure = 1
> Hypertension AND Heart Failure = 2
> ...

I assume you want the other option, since it's what makes more sense. In that case, the solution is indeed to encode each comorbidity as a binary feature.
I understand you're concerned about the dimensionality growing. One thing you can do is to make the input sparse (`sp.sparse`) - for sparse inputs, we only perturb non-zero columns, so you would not get an explanation that says 'the absence of this comorbidity is important', but would be much more efficient in number of samples.

**Comment by bvanberl** [comment]
Hi Mr. Ribeiro, thank you very much for your thoughtful response. I will try this out with sparse inputs!
