### ISSUE TITLE
Multithreading with Python

### ISSUE THREAD

**Issue by khawkhaa** [marcotcr/lime#451]
I am asking the same question https://github.com/marcotcr/lime/issues/82.
Is Lime package still not suitable for Multithreading with Python?

**Comment by marcotcr** [comment]
I haven't actually tried computing two explanations on different threads. If you have, what error do you get?

**Comment by khawkhaa** [comment]
I have more than 10.000 examples to run.
I have detailed my errors in this post https://stackoverflow.com/questions/61313856/multithreading-lime-in-python

**Comment by marcotcr** [comment]
you should create a dummy function instead of explain.explain_instance, which just calls your prediction function a bunch of times. This way, you will figure out if your model works with joblib (my guess is that it doesn't, from your error message).
If you have a function that you know can be parallelized and the error is due to LIME, reopen please : )
