### ISSUE TITLE
How can I validate LIME's outputs?

### ISSUE THREAD

**Issue by mh2t** [marcotcr/lime#452]
I simulated a data set with pre-correlation matrix, and known true trajectory function (equation). I simulated target y with continuous and binary variables. I wanted to train a classifier like GBM, and interpret the model by LIME. I was wondering how I can validate the outputs I get from LIME based on the true weights I have specified on my simulated data. Your help would be deeply appreciated.

**Comment by marcotcr** [comment]
two things to note here:
1. LIME will give you an explanation for what your model is doing, not what the _true_ label function is. It's not clear from your question if you want to validate what LIME is doing or what the model is doing. If you want the former, you should use the function that generates y with LIME rather than a model learned on it.
2. LIME will give you a local approximation, which is supposed to be good in the neighborhood of the example being explained but not guaranteed to be good elsewhere. If your function is linear, it won't matter. You can easily create a nonlinear response of a certain feature such that a good linear explanation in a point is completely wrong for a lot of other points in the input space  (think of a parabola, for example).

If this doesn't answer your question, feel free to comment and I'll reopen the issue.

**Comment by mh2t** [comment]
Thanks a lot for your insightful answers. I'm willing to investigate what LIME is doing by using true function that generates y with LIME. Then I compare weights estimated by LIME. So If I construct LIME for every individual n observations, what should I expect for n number of weights coming from LIME? Can I expect the average of n weights for each feature is the same as the corresponding features' weights in the true function?

**Comment by marcotcr** [comment]
> Can I expect the average of n weights for each feature is the same as the corresponding features' weights in the true function?

I guess it depends on how you define 'feature weights in the true function'. I think you can't expect this in general, it depends on what the function looks like.
