### ISSUE TITLE
Problem with interpretation of SP-LIME

### ISSUE THREAD

**Issue by donghwan92** [marcotcr/lime#509]
I am using LIME (especially SP-LIME) methodologies to interpret machine learning.

As far as I know, SP-LIME extracts only representative samples, enabling a global interpretation of the model.

I wonder how i can do a global interpretation, even if you only take representative samples, each sample has different results.

The 'W' in your code is the result of only representative samples as shown in the figure below. However, it can be seen that each sample has different values.

![image](https://user-images.githubusercontent.com/54572383/93161590-d0739680-f74d-11ea-99fc-1e2989140681.png)

Can I interpret the average value of each variable as a global interpretation value?

I would appreciate your reply ! Thank you

**Comment by marcotcr** [comment]
SP-LIME explicitly tries to select different samples that are diverse (not repetitive), so you can get a sense of different behaviors of the model. I don't think it makes sense to average the values coming from SP-lime. You can average the values of all explanations, being careful to take `np.abs` so that negative and positive weights don't cancel out.
