### ISSUE TITLE
Combining LIME with Gradient Boosted Models

### ISSUE THREAD

**Issue by skirmer** [marcotcr/lime#51]
Hello! A colleague and I are working on implementing the LIME strategy with ML models using gradient boosting (LightGBM right now, although we use XGBoost a lot.) However, we've run into some snags getting the explain_instance function on the LimeTabularExplainer to work with a gradient boosted model prediction.

I'm attaching some code to illustrate, using the iris dataset that you use in some of your own tutorials. (The model is a silly example, but the resulting error is the point.) It'll require installing LightGBM to operate. We're using pretty massive datasets, predicting a binary outcome, and gradient boosted models are our bread and butter, so if you have advice on getting a gbm to play nice with LIME we would be grateful!

Specific errors being thrown: "ValueError: cannot reshape array of size 20000 into shape (1,1)", 

"ValueError: Found input variables with inconsistent numbers of samples: [5000, 1]". 

thanks!
Stephanie

[demo_for_issue.txt](https://github.com/marcotcr/lime/files/825876/demo_for_issue.txt)

**Comment by marcotcr** [comment]
Hello,
I installed LightGBM, but I wasn't able to run your example, or get LightGBM to train a multiclass model. In any case, it seems the problem is in this line if your predict_fn:
`pr = bst.predict(x.reshape(1,-1)) `

If the problem has K features and C classes, LimeTabular assumes the predict function will take as input a N * K array, and output a N * C array with prediction probabilities.
You are reshaping x so that it is 1 * (N * K).

It seems that lightGBM's multiclass predict function should work directly into LIME, as it seems to output a matrix (I'm not sure because I could not get it to work). For binary classification, it only outputs a 1d array, so you need to do something like:
```
def predict_fn(x):
    preds = gbm.predict(x).reshape(-1, 1)
    p0 = 1 - preds
    return np.hstack((p0, preds))
```

[Here](https://drive.google.com/open?id=0ByblrZgHugfYdWliODcyT0N3VDg) is an example where I just took lightgbm's binary classification tutorial and explained a prediction from it (the notebook uses data in the lightgbm repository).

Let me know if this helps.

**Comment by marcotcr** [comment]
An addendum: I use an xgboost classifier in [this tutorial](http://marcotcr.github.io/lime/tutorials/Tutorial%20-%20continuous%20and%20categorical%20features.html) and in many other applications, so I don't think you should have any trouble with it (but please tell me if you do).

**Comment by skirmer** [comment]
Thanks so much for taking a look at it, Marco- I appreciate it! I will be working on this again at the office tomorrow and I'll see if I can get it working.

**Comment by skirmer** [comment]
Hi again Marco- your solution works beautifully! The prediction function wrapper seems to be the key, I just didn't have it structured correctly. Thank you so much!
