### ISSUE TITLE
Problem with SP formula in article and code

### ISSUE THREAD

**Issue by eescriva** [marcotcr/lime#512]
Hi,
I'm studying your SP-LIME method in the article and the code, and I don't understand why the code line and the formula below are equals:

`current = np.dot((np.sum(abs(W)[V + [i]], axis=0) > 0), importance)  # coverage function`
![image](https://user-images.githubusercontent.com/34377393/93601417-78dd6100-f9c1-11ea-84eb-c3024ff2c608.png)

Why did you check if the sum of absolute value of W is > 0 ? Where is that part in the math formula ?

Thank you for your answer !

**Comment by marcotcr** [comment]
The code is the vectorized version of the formula you listed. `abs(W)[V + [I]]` is getting `W[i]` for `i` in `V` (in this case, the new V' with the added element). We're checking absolute values because weights can also be negative, as we say in the third paragraph of section 4 in the paper.
Checking if the sum is greater than zero is the same as checking if any element is greater than 0 (this is what is inside the brackets in the indicator function). This returns a boolean vector, which is multiplied by the importance.

**Comment by marcotcr** [comment]
A good way of convincing yourself that this is the case is creating your own `W`, `V`, and `I`, and running it through this code
