### ISSUE TITLE
Normal(0,1) instad of Uniform(0,1)?

### ISSUE THREAD

**Issue by MartinSchmitzDo** [marcotcr/lime#55]
Dear All,

i am currently investigating the toolkit and get the concepts. I am wondering for the reason to use normal distributed numbers in the generation of random data. Naturally i would go for 0-1 normalization and use uniformly distributed data to not get a bias towards the center?

Best,
Martin

**Comment by christophM** [comment]
If you would do this, then you would get data points uniformly distributed from the whole range of the dataset, and that is not what you want. With this kind of sampling you would try to fit a global model and try to get  an explanation for the whole black box (which will likely not work well, unless for the classification task an easier model would have been good enough in the first place). 

The sampling should be **local** (=normal distribution, mass in the center) around the data point you want to explain, because you want to learn a local model. 
The intuition is: An explanation for a certain classification can be done by making **small changes** to the features and observing/ learning how the black box model's classification changes for the new data points. Again small changes equals bias towards the center. 

Hope that answers your question.

**Comment by MartinSchmitzDo** [comment]
Dear Christoph,

so the uniform(0,1) is centered arount the data point i want to get explained? It looks like it's centered around the mean of the training data, which would be missleading?

Regarding your point. If i add weights to my instances using euclidian distance to my data point i already introduce a gaussian like shape around the point i want to predict. The closer to the point the more weight it gets. Thus most of my weight are around the prediction point. Doing Normal(0,1) and weights is doing the same thought twice, isnt it?

Best,
Martin

**Comment by christophM** [comment]
I think you are right Martin. I just checked the code and indeed it draws around the overall training mean with standard deviation of the training data. And later the sampled instances get weighted by the Kernel function. So a data point you want to have explained could have a feature value far away from the mean and then you could end up with very little data points that are actually in the neighbourhood and get poor estimations. 

So I think your suggestion of simply sampling the whole space uniformly makes sense. Then you avoid having the cluster in the center. The other option would be to sample in the neighbourhood, by sampling from N(0,1) by multiplying with some standard devation (for example from the training data) and adding the mean of the data point (and not the overall mean).

For number of samples n -> Inf, all three methods should yield the same results, but sampling uniformly should be more efficient (needing less samples for same estimation confidence) than drawing around the center (unless the data point is in the center). Maybe sampling directly around the data point might be even more efficient, but only if you make the neighbourhood big enough (standard deviation of the normal distribution). If you make it very big, it should converge towards the uniform sampling solution.

**Comment by MartinSchmitzDo** [comment]
Dear Christoph,

thanks for responding. I agree that with n->inf it does not matter. I see in general a issue of spareness. Given a lot of dimensions (>100 in Text Mining) one would need to generate quite some points. My intuitive approach of using a normal distribution for each example is a bit worse in runtime than taking taking a somewhat centered distribution around the single point. But for the normal distribution i am concerned to get a bias.

And other the point. I would like to have one parameter of the algorithm defining "locality", which is a key factor for the whole algorithm and hard to determine automatically. On the one hand you do not want to built a too global model on the other hand you do not want to extract importances from a "random dip" in the decision boundary. What would you use for it - the kernel_width?

~Martin

**Comment by marcotcr** [comment]
The reason I chose not to sample from the uniform is because in some domains the range is very very large. Again, if we draw infinite samples this doesn't matter due to the kernel, but it does matter for a limited number of samples. It is a trade-off - do we want to bias it towards the mean or require more samples? I don't know what the right answer is. For text mining, one would not use TabularExplainer anyway.

To your second point: yes, the kernel width is what determines locality, together of course with the distance function. I think most people would use euclidean for tabular data and cosine for text data, so adjusting the kernel width is what gives you different levels of locality.

**Comment by MartinSchmitzDo** [comment]
Hi Marco,

the problem of Normal(0,1) is that any learner will try to predict more points better. Thus you introduce a bias towards the origin of the centered data. If you want to explain a data point far away from the center of the distribution(s) you might get unwanted results. In fact you get explanations which are biased towards explanations of the average data point.
But of course i agree with the curse of dimensionality if you want to draw Uniform(0,1). A solution would to draw around the data point, but I have not yet a good argument for the distribution and the parameters of it (for normal the variance).

Regarding locality factor: My initial intuition was to use 1/pow(distance,k) where k would be the "Locality Factor" before i saw your kernel. I think the provided standard kernel is a bit nicer (and more general) but stacks up to have two locality mechanisms (kernel choice and distance metric). I guess that's fine..

Best,
Martin

**Comment by marcotcr** [comment]
Yes, I understand the bias. I don't know what the best solution is, but in most applications I think this shouldn't matter much anyway : ).
I'm closing this issue, but feel free to reopen if any more questions / comments pop up.
