### ISSUE TITLE
LIME with object detection models

### ISSUE THREAD

**Issue by emamangiapia** [marcotcr/lime#614]
Hi, is it possible to use LIME (or Anchors) with object detection models? Such as: faster RCNN, Yolo etc. If yes, which modifications should be done?

**Comment by marcotcr** [comment]
If you have a continuous or categorical function to explain, e.g. 'the probability that the object is in the image', you can just use LimeTabularExplainer as is (you'd just have to wrap the output of the object detection model so that it produces this output).
If you are thinking of explaining the boundaries themselves, I don't know how I'd go about doing that.
