### ISSUE TITLE
Binary Indicator vs Output probabilities

### ISSUE THREAD

**Issue by anisham197** [marcotcr/lime#615]
I see that the paper mentions that we can use a binary indicator for f(x) instead of a probability.
> f(x) is the probability (or a binary indicator) that x belongs to a certain class

I do not see code examples where a binary indicator is used instead of a probability i.e. a model outputs only 0 and 1 labels instead of probabilities of the 2 classes

I am trying to understand how using a binary indicator vs probabilities would affect LIME's explanations? Is there a reason probabilities are preferred over binary indicators?

**Comment by marcotcr** [comment]
The way to do it would be to just reshape predictions into probabilities that are always 0 or 1. We prefer probabilities (when available) because they allow us to use the signal from changes in prediction probability that do not necessarily change the prediction (e.g. if you change P(1) from 1 to 0.6, that has signal that we can use for explanation, perhaps more than if you change from 0.51 to 0.49)
