### ISSUE TITLE
Queries regarding distance function

### ISSUE THREAD

**Issue by lumliolum** [marcotcr/lime#629]
Hello,
I don't know if this is the right place to ask my queries (If this is not the correct place, I will delete the issue created). I have been reading the LIME paper and code (Mostly LIME tabular and text) to understand the implementation. I have some queries on the distance function used.
We are calculating the distance between samples in interpreted space (that is `{0,1}` space). So why do we use L2 distance in tabular data and cosine distance in text data?

and also in the code [here](https://github.com/marcotcr/lime/blob/master/lime/lime_text.py#L468).

```python
def distance_fn(x):
    return sklearn.metrics.pairwise.pairwise_distances(
        x, x[0], metric=distance_metric).ravel() * 100
```
The code snippet is from the lime text. 
Why are authors multiplying the distance with `100`?

**Comment by marcotcr** [comment]
> We are calculating the distance between samples in interpreted space (that is {0,1} space). So why do we use L2 distance in tabular data and cosine distance in text data?  

You'll notice that for tabular we use scaled data rather than the interpretable representation. We want the distance function to be meaningful, i.e. for it to roughly correspond to how we perceive distances between examples. I thought that cosine for text and L2 for tabular data was what made the most sense, given that.

>Why are authors multiplying the distance with 100?

Ha, I don't remember. It probably has to do with the default value for the kernel width, but I don't know anymore : )
