### ISSUE TITLE
show_in_notebook() flips positive/negative values when labels or top_labels is specified

### ISSUE THREAD

**Issue by kennysong** [marcotcr/lime#633]
`show_in_notebook()` seems to have a bug if the explanation is generated for a "0" label rather than a "1".

What the explanation should look like:

<img width="553" alt="Screen Shot 2021-08-08 at 4 54 01 PM" src="https://user-images.githubusercontent.com/2199875/128625082-a32f9e58-504a-4e67-8e8c-80bb34efe840.png">

What it looks like if you specify `labels=[0]` or `top_labels=1` in `explain_instance()`:

<img width="549" alt="Screen Shot 2021-08-08 at 4 54 44 PM" src="https://user-images.githubusercontent.com/2199875/128625100-1ae8660f-1835-4683-9047-f9e61e0ead29.png">

[Here's a Colab notebook to reproduce](https://colab.research.google.com/drive/1dLFn1ro5fiEvJRF4D6apf9nx698hzk8z?usp=sharing), based on the tutorial notebook `Lime - basic usage, two class case.ipynb`.

**Comment by marcotcr** [comment]
This is indeed a bug, due to a hack I added to the javascript where I assume that if you have binary classification you'd always want to see the same plot with label 0 on the left and label 1 on the right. 
I think I just won't fix it, as I think that is a fair assumption and people should just use `labels=(1,)` if they're doing binary classification (I should document it though).

Thanks!!
