### ISSUE TITLE
lime for text: does it work for ngram instead unigram?

### ISSUE THREAD

**Issue by lampts** [marcotcr/lime#7]
I tried to use bigram or ngram from tfidf but it seems that lime just indexed the unigram. Is this true? How can we highlight the ngram in the text?

Thank you for such a amazing package.

**Comment by marcotcr** [comment]
At the moment, we restrict the explanation terms to unigrams, even if the model is using bigrams or ngrams. However, if a particular bigram is important, LIME should highlight both words separately. I've seen this effect using bigrams, and also using LIME with models like LSTMs.

One think you want to do is set bow=False in the constructor if you're not using unigrams. This ensures that we don't remove all occurrences of a word at the same time when perturbing the instance (which messes up bigrams), and also that we replace words by an UNK symbol instead of removing them (so as to not create spurious n-grams).

If the results are not making sense, please let me know : )
Thanks,
